# Jekyll configuration
title: INSPIRE data specification extensions by wetransform
name: INSPIRE Data Specification Extensions
description: Inventory of existing INSPIRE Model Extensions, extension pattern catalogue and end-to-end tutorial project
author:
  name: Thorsten Reitz
  email: tr@wetransform.to

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

# Separator for post excerpts
excerpt_separator: <!--more-->

# Default permalink style
permalink: pretty

pygments: false

# Defaults
defaults:
  -
    scope:
      path: "inventory" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "inventory"
  -
    scope:
      path: "pattern" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "pattern"
