# Jekyll configuration
title: INSPIRE Data Specification Extensions
name: INSPIRE Data Specification Extensions
description: Inventory of existing INSPIRE Model Extensions, extension pattern catalogue and end-to-end tutorial project
author:
  name: Thorsten Reitz
  email: tr@wetransform.to

# Markdown library to use
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: "inventory" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "inventory"
  -
    scope:
      path: "pattern" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "pattern"
